services:
  backend:
    image: ${AWS_ECR_LOGIN_URI}/${ECR_BACKEND_REPO}:${IMAGE_TAG}
    container_name: dietplanner-backend
    ports:
      - "8000:8000"
    restart: always
    environment:
      NVIDIA_API_KEY: ${NVIDIA_API_KEY}
      PINECONE_API_KEY: ${PINECONE_API_KEY}

  frontend:
    image: ${AWS_ECR_LOGIN_URI}/${ECR_FRONTEND_REPO}:${IMAGE_TAG}
    container_name: dietplanner-frontend
    ports:
      - "80:80"  # Changed from 80:5173
    depends_on:
      - backend
    restart: always