services:
  backend:
    # Service name is 'backend', so Nginx can call http://backend:8000
    image: ${AWS_ECR_LOGIN_URI}/${ECR_BACKEND_REPO}:${IMAGE_TAG}
    container_name: dietplanner-backend
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      INTENT_MODEL_PATH: /app/Backend/src/IntentLLM/IntentLLM-F/export_results/checkpoint-500
      PYTHONPATH: /app/Backend/src
      PYTHONUNBUFFERED: "1"
      NVIDIA_API_KEY: ${NVIDIA_API_KEY} 
      PINECONE_API_KEY: ${PINECONE_API_KEY} 
    volumes:
      - uploads_data:/app/uploads

  frontend:
    image: ${AWS_ECR_LOGIN_URI}/${ECR_FRONTEND_REPO}:${IMAGE_TAG}
    container_name: dietplanner-frontend
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - backend

volumes:
  uploads_data: