services:
  backend:
    image: ${AWS_ECR_LOGIN_URI}/${ECR_BACKEND_REPO}:${IMAGE_TAG}
    container_name: dietplanner-backend
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      INTENT_MODEL_PATH: /app/Backend/src/IntentLLM/IntentLLM-F/export_results/checkpoint-500
      PYTHONPATH: /app/Backend/src
      PYTHONUNBUFFERED: "1"
      NVIDIA_API_KEY: ${NVIDIA_API_KEY} 
      PINECONE_API_KEY: ${PINECONE_API_KEY} 
    volumes:
      - uploads_data:/app/uploads

  frontend:
    image: ${AWS_ECR_LOGIN_URI}/${ECR_FRONTEND_REPO}:${IMAGE_TAG}
    container_name: dietplanner-frontend
    ports:
      - "80:80"
      - "443:443"  # ✅ ADDED: Open secure port
    restart: unless-stopped
    depends_on:
      - backend
    volumes:
      # ✅ ADDED: Share certificates with Nginx
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

  # ✅ ADDED: New service to handle SSL Certificates
  certbot:
    image: certbot/certbot
    container_name: dietplanner-certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    # This command checks for renewal every 12 hours
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  uploads_data: