services:
  backend:
    image: ${AWS_ECR_LOGIN_URI}/${ECR_BACKEND_REPO}:${IMAGE_TAG}
    container_name: dietplanner-backend
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      PYTHONPATH: /app/Backend/src
      PYTHONUNBUFFERED: "1"
    volumes:
      - uploads_data:/app/uploads

  frontend:
    image: ${AWS_ECR_LOGIN_URI}/${ECR_FRONTEND_REPO}:${IMAGE_TAG}
    container_name: dietplanner-frontend
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - backend

volumes:
  uploads_data:
